config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from rent import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rent/', include('rent.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    path('pybo/', include('pybo.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

rent/urls.py
from django.urls import path
from . import views

app_name = 'rent'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:place_id>/', views.detail, name='detail'),
    path('place/create/', views.place_create, name='place_create'),
    path('place/modify/<int:place_id>/', views.place_modify, name='place_modify'),
    path('place/delete/<int:place_id>/', views.place_delete, name='place_delete'),
    path('rentinfo/', views.info_index, name='rentinfo_index'),
]

rent/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Place(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    pcode = models.CharField(max_length=10)
    pname = models.TextField()
    location = models.TextField()
    price = models.IntegerField(default=0)
    # 추가
    side = models.TextField()
    ball = models.TextField()
    vest = models.TextField()
    # 추가 항목(media)
    imgfile = models.ImageField(null=True, blank=True)
    modify_date = models.DateTimeField(null=True, blank=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.pcode + ' ' + self.pname + ' ' + self.location + ' ' + str(self.price)

class RentInfo(models.Model):
    pcode = models.CharField(max_length=10)
    pname = models.TextField()
    price = models.IntegerField(default=0)
    r_date = models.DateTimeField()

    def publish(self):
        self.p_date = timezone.now()
        self.save()

# Create your models here.

rent/forms.py
from django import forms

from rent.models import Place, RentInfo


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ['pcode', 'pname', 'location', 'price', 'side', 'ball', 'vest', 'imgfile']
        labels = {
            'pcode': '풋살장 코드',
            'pname': '풋살장 이름',
            'location': '지역',
            'price': '가격',
            'side': '실내/실외',
            'ball': '공대여',
            'vest': '조끼대여',
            'imgfile': '이미지',
        }

class RentInfoForm(forms.ModelForm):
    class Meta:
        model = RentInfo
        fields = ['pcode', 'pname', 'price', 'r_date']
        labels = {
            'pcode': '풋살장 코드',
            'pname': '풋살장 이름',
            'price': '대여가격',
            'r_date': '대여날짜'
        }

rent/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.http import HttpResponse
from .models import Place,RentInfo
from .forms import PlaceForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q, Count

def index(request):

    """
    rent 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page', '1')     # 페이지
    kw = request.GET.get('kw', '')      # 검색어
    so = request.GET.get('so', 'recent')    # 정렬 기준

    if so == 'recommend':
        place_list = Place.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', 'pcode')
    elif so == 'popular':
        place_list = Place.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', 'pcode')
    else:  # recent
        place_list = Place.objects.order_by('pcode')

    # 조회
    if kw:
        place_list = place_list.filter(
            Q(location__icontains=kw) |                      # 제목 검색
            Q(pname__icontains=kw)                       # 내용 검색
        ).distinct()

    paginator = Paginator(place_list, 10)
    page_obj = paginator.get_page(page)
    context = {'place_list' : page_obj}
    return render(request, 'rent/place_list.html', context)

def detail(request,place_id):
    """
    rent 내용 출력
    """
    place = get_object_or_404(Place, pk=place_id)
    context = {'place': place}
    return render(request, 'rent/place_detail.html', context)

@login_required(login_url='common:login')
def place_create(request):
    """
    place 제품 등록
    """
    if request.method == 'POST':
        form = PlaceForm(request.POST, request.FILES)
        if form.is_valid():
            place = form.save(commit=False)
            place.author = request.user # 추가한 속성 author 적용
            place.save()
            return redirect('rent:index')
    else:
        form = PlaceForm()
    context = {'form': form}
    return render(request, 'rent/place_form.html', context)

@login_required(login_url='common:login')
def place_modify(request, place_id):
    """
    place 제품 수정
    """
    place = get_object_or_404(Place, pk=place_id)
    if request.user != place.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('rent:detail', place_id=place.id)

    if request.method == "POST":
        form = PlaceForm(request.POST, request.FILES, instance=place)
        if form.is_valid():
            place = form.save(commit=False)
            place.author = request.user
            place.modify_date = timezone.now()  # 수정일시 저장
            place.save()
            return redirect('rent:detail', place_id=place.id)
    else:
        form = PlaceForm(instance=place)
    context = {'form': form}
    return render(request, 'rent/place_form.html', context)


@login_required(login_url='common:login')
def place_delete(request, place_id):
    """
    place 제품 삭제
    """
    place = get_object_or_404(Place, pk=place_id)
    if request.user != place.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('rent:detail', place_id=place.id)
    place.delete()
    return redirect('rent:index')


def info_index(request):

    """
    rent 목록 출력
    """
    # 입력 인자
    page = request.GET.get('page', '1')     # 페이지
    kw = request.GET.get('kw', '')      # 검색어
    so = request.GET.get('so', 'recent')    # 정렬 기준

    if so == 'recommend':
        rentinfo_list = RentInfo.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', 'r_date')
    elif so == 'popular':
        rentinfo_list = RentInfo.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', 'r_date')
    else:  # recent
        rentinfo_list = RentInfo.objects.order_by('-r_date')

    # 조회
    if kw:
        rentinfo_list = rentinfo_list.filter(
            Q(pcode__icontains=kw) |                      # 제목 검색
            Q(pname__icontains=kw)                       # 내용 검색
        ).distinct()

    paginator = Paginator(rentinfo_list, 10)
    page_obj = paginator.get_page(page)
    context = {'rentinfo_list' : page_obj}
    return render(request, 'rent/rentinfo_list.html', context)

templates/rent/place_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="text-center" style="background-color : #A5DE9F;">풋살장 코드 : {{ place.pcode }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div aria-colspan="2">
                {% if place.imgfile != '' and place.imgfile != null %}
                    <img src="{{ place.imgfile.url }}" style="max-width:400px">
                {% else %}
                    <div>첨부된 사진이 없습니다.</div>
                {% endif %}

            </div>
            <div class="card-text" style="white-space: pre-line;">풋살장 이름 : {{ place.pname }}</div>
            <div class="card-text" style="white-space: pre-line;">지역 : {{ place.location }}</div>
            <div class="card-text" style="white-space: pre-line;">가격 : {{ place.price }}</div>
            <div class="card-text" style="white-space: pre-line;">실내/실외 : {{ place.side }}</div>
            <div class="card-text" style="white-space: pre-line;">공대여 : {{ place.ball }}</div>
            <div class="card-text" style="white-space: pre-line;">조끼대여 : {{ place.vest }}</div>
            <div class="card-text" style="white-space: pre-line;">
                   {{ place.author.username}}
            </div>
            {% if request.user == place.author %}
            <div class="my-3">
                <a href="{% url 'rent:place_modify' place.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'rent:place_delete' place.id  %}">삭제</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/rent/place_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2" style="background-color: #CFFF24; text-align : center">풋살장 등록</h5>
    <form method="post" class="post-form my-3" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- 오류표시 Start -->
    {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="form-group">
        <label for="pcode">풋살장 코드</label>
        <input type="text" class="form-control" name="pcode" id="pcode"
               value="{{ form.pcode.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        <label for="pname">풋살장 이름</label>
        <input type="text" class="form-control" name="pname" id="pname"
               value="{{ form.pname.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        <label for="location">지역</label>
        <input type="text" class="form-control" name="location" id="location"
               value="{{ form.location.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        <label for="price">가격</label>
        <input type="text" class="form-control" name="price" id="price"
               value="{{ form.price.value|default_if_none:'' }}">
    </div>
        <div class="form-group">
        <label for="side">실내/실외</label>
        <input type="text" class="form-control" name="side" id="side"
               value="{{ form.side.value|default_if_none:'' }}">
    </div>
        <div class="form-group">
        <label for="ball">공대여</label>
        <input type="text" class="form-control" name="ball" id="ball"
               value="{{ form.ball.value|default_if_none:'' }}">
    </div>
        <div class="form-group">
        <label for="vest">조끼대여</label>
        <input type="text" class="form-control" name="vest" id="vest"
               value="{{ form.vest.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        <label for="imgfile" class="col-form-label">풋살장 사진</label>
        <input class="form-control" type="file" name="imgfile" id="imgfile">
    </div>
    <button type="submit" class="btn btn-primary">등록하기</button>
</form>
</div>
{% endblock %}

templates/rent/place_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h3 style="text-align : center">풋살장 관리 시스템</h3>
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class = "text-center" style="background-color : #CFFF24;">
            <th>풋살장 코드</th>
            <th>풋살장 이름</th>
            <th>지역</th>
            <th>가격</th>
            <th>실내/실외</th>
            <th>공대여</th>
            <th>조끼대여</th>
            <th>이미지</th>
            <th>작성자</th>
        </tr>
        </thead>
        <tbody>
        {% if place_list %}
        {% for place in place_list %}
        <tr class="text-center">
            <td>
                <a>{{ place.pcode }}</a>
            </td>
            <td><a href="{% url 'rent:detail' place.id %}">{{ place.pname }}</a></td>
            <td>{{ place.location }}</td>
            <td>{{ place.price }}</td>
            <td>{{ place.side }}</td>
            <td>{{ place.ball }}</td>
            <td>{{ place.vest }}</td>
            <td class="text-truncate" style="max-width: 100px;">
                {% if place.imgfile != '' and place.imgfile != null %}
                <span class="badge badge-secondary py-1">
                    O
                </span>
                {% else %}
                <span class="badge badge-secondary py-1">
                    X
                </span>
                {% endif %}
            </td>
            <td>{{ place.author.username }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">풋살장이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if place_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ place_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in place_list.paginator.page_range %}
        {% if page_number >= place_list.number|add:-5 and page_number <= place_list.number|add:5 %}
            {% if page_number == place_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if place_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ place_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'rent:place_create' %}" class="btn btn-primary">
        풋살장 등록하기
    </a>
</div>
<form id="searchForm" method="get" action="{% url 'rent:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

        $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/rent/rentinfo_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h3 style="text-align : center">풋살장 대여 관리 시스템</h3>
    <div class="row justify-content-end my-3">
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class = "text-center" style="background-color : #CFFF24;">
            <th>풋살장 코드</th>
            <th>풋살장 이름</th>
            <th>가격</th>
            <th>대여날짜</th>
        </tr>
        </thead>
        <tbody>
        {% if rentinfo_list %}
        {% for rentinfo in rentinfo_list %}
        <tr class="text-center">
            <td>
                <a>{{ rentinfo.pcode }}</a>
            </td>
            <td><a href="{% url 'rent:detail' rentinfo.id %}">{{ rentinfo.pname }}</a></td>
            <td>{{ rentinfo.price }}</td>
            <td>{{ rentinfo.r_date }}</td>

        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">대여된 내역이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if rentinfo_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ rentinfo_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in rentinfo_list.paginator.page_range %}
        {% if page_number >= rentinfo_list.number|add:-5 and page_number <= rentinfo_list.number|add:5 %}
            {% if page_number == rentinfo_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if rentinfo_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ rentinfo_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'rent:place_create' %}" class="btn btn-primary">
        대여 내역 등록하기
    </a>
</div>
<form id="searchForm" method="get" action="{% url 'rent:rentinfo_index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

        $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}